<a href="https://colab.research.google.com/github/danylonepochatov/calculator/blob/main/Nepochatov_Danylo__9_1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [4]:
# Do not edit this cell

import numpy as np
import pandas as pd

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [ ]:
res = np.array([1,2,3,4,5])

print(res)

[1 2 3 4 5]


In [ ]:
res2 = np.arange(1,6)

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [2]:
res3 = np.random.randint(1,101, size = (3,5))

print(res3)

[[58 38 63 16 31]
 [28 17 17 16 61]
 [39 27 95 94 58]]


### Task 3

Print the first row of array `res3`.

In [ ]:
print(res3[0])

[81 83 77 34 80]


### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [ ]:
print(res3[:, -1])

[80 71 75]


### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [ ]:
# Min
res_min = np.min(res3[:, 1])

print('min =', res_min)

min = 9


In [ ]:
# Max
res_max = np.max(res3[:, 1])

print('max =', res_max)

max = 83


In [ ]:
# Sum
res_sum = np.sum(res3[:, 1])

print('sum =', res_sum)

sum = 122


### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [ ]:
x = np.arange(0, 1.01, 0.1)
f_x = np.exp(2 * x)

print(f_x)

[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [5]:
df = pd.read_csv("https://web.stanford.edu/class/cs102/datasets/Titanic.csv")

### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [6]:
df.columns

Index(['last', 'first', 'gender', 'age', 'class', 'fare', 'embarked',
       'survived'],
      dtype='object')

In [7]:
df.head(10)

last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  Southampton      yes  
3  53.1000  Southampton      yes  
4   8.0500  Southampton       no  
5   8.4583   Queenstown       no  
6  51.8625  Southampton       no  
7  21.0750  Southampton       no  
8  11.1333  Southampton      yes  
9  30.0708    Cherbourg      yes

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [12]:
df['full name'] = df['last'] + ' ' + df['first']
df.head(5)

last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   

      fare     embarked survived  \
0   7.2500  Southampton       no   
1  71.2833    Cherbourg      yes   
2   7.9250  Southampton      yes   
3  53.1000  Southampton      yes   
4   8.0500  Southampton       no   

                                           full name  
0                             Braund Mr. Owen Harris  
1  Cumings Mrs. John Bradley (Florence Briggs Tha...  
2                               Heikkinen Miss Laina  
3        Futrelle Mrs. Jacques Heath (Lily May Peel)  
4                            Allen Mr. William Henry

### Task 10

Remove the two original columns - last, first.

In [23]:
df.drop(['first', 'last'], axis = 1, inplace=True)
cols = df.columns.tolist()
cols.remove('full name')
cols = ['full name'] + cols
df = df[cols]
df.head(5)

full name gender   age  class  \
0                             Braund Mr. Owen Harris      M  22.0      3   
1  Cumings Mrs. John Bradley (Florence Briggs Tha...      F  38.0      1   
2                               Heikkinen Miss Laina      F  26.0      3   
3        Futrelle Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4                            Allen Mr. William Henry      M  35.0      3   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  Southampton      yes  
3  53.1000  Southampton      yes  
4   8.0500  Southampton       no

### Task 11

Calculate the total number of survivors in the dataset.

In [27]:
total_survivors = (df['survived'] == 'yes').sum()
print(total_survivors)

342
